# [START runtime]
runtime: nodejs
service: famouswall
env: flex
# [END runtime]
# [START handlers]
handlers:
  - url: /
    secure: always
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)
    secure: always
    static_files: build/\1
    upload: build/(.*)
# [END handlers]